/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
	country, 
	count(customer_key) as total_customers
from gold.dim_customers
group by country
order by count(customer_key) desc

-- Find total customers by gender
select 	
	gender,
	count(customer_key) as total_customers
from gold.dim_customers
group by gender 
order by count(customer_key) desc

-- Find total products by category
select 
	category,
	count(product_key) as total_products
from gold.dim_products
group by category 
order by count(product_key) desc

-- What is the average costs in each category?
select 
	category,
	round(avg(cost), 2)  as avg_cost
from gold.dim_products 
group by category 
order by avg(cost) desc

-- What is the total revenue generated for each category?
select 
	p.category,	
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key 
group by p.category
order by sum(f.sales_amount) desc

-- What is the total revenue generated by each customer?
select 
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key 
group by 
	c.customer_key,
	c.first_name,
	c.last_name
order by sum(f.sales_amount) desc

-- What is the distribution of sold items across countries?
select 
	c.country,
	sum(f.quantity) as total_sold_item
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key 
group by 
	c.country
order by sum(f.quantity) desc
